ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from products import views
from django.conf import settings
from django.conf.urls.static import static
from carts import views as cartviews
from orders import views as orderviews
from accounts import views as accountviews

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home, name='home',),
    url(r'^products/$', views.all, name='allproducts',),
    url(r'^products/(?P<slug>[\w-]+)/$', views.single, name="single"),
    url(r'^s/$', views.search, name='search',),
    url(r'^cart/$', cartviews.view, name='cart',),
    url(r'^cart/(?P<slug>[\w-]+)/$', cartviews.add_to_cart, name='add_to_cart'),
    url(r'^cart/(?P<id>\d+)/$', cartviews.remove_from_cart, name='remove_from_cart'),
    url(r'^checkout/$', orderviews.checkout, name='checkout',),
    url(r'^orders/$', orderviews.orders, name='user_orders',),
    url(r'^accounts/logout/$', accountviews.logout_view, name='auth_logout'),
    url(r'^accounts/login/$', accountviews.login_view, name='auth_login'),
    url(r'^accounts/register/$', accountviews.registration_view, name='auth_register'),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', accountviews.activation_view, name="activation_view"),
    url(r'^ajax/add_user_address/$', accountviews.add_user_address, name="ajax_add_user_adddress"),
    url(r'^accounts/address/add/$', accountviews.add_user_address, name="add_user_address"),
    url(r'^checkout/payment/$', orderviews.payment_view, name='payment',),
    url(r'^schools/$', views.allSchools, name='allschools'),
    url(r'^product/shirts-view-all/$', views.view_all_shirt, name='p7-products'),
    url(r'^products/skirt-view-all/$', views.view_all_skirt, name='skirt-product'),
    url(r'^products/belt-view-all/$', views.view_all_belt, name='belt-product'),
    url(r'^products/socks-view-all/$', views.view_all_socks, name='sock-product'),
    url(r'^products/trousers-view-all/$', views.view_all_trousers, name='trousers-product'),
    # url(r'^category/(?P<category_id>\d+)/$', views.get_product_by_category, name='product-by-category',),
    # url(r'^products/category/(?P<slug>[\w-]+)/$', views.get_product_by_category, name="product-by-category"),
    # url(r'^(?P<category_slug>[-\w]+)/$', views.marketplaceHome, name='products_by_category'),

    # url('<slug:slug>/', views.category_detail, name='category_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/orders/models.py
from django.db import models
from carts.models import Cart
from django.conf import settings
from decimal import Decimal
from accounts.models import UserAddress

# Create your models here.

settings.AUTH_USER_MODEL

STATUS_CHOICES = (
        ("Started", "Started"),
        ("Abandoned", "Abandoned"),
        ("Finished", "Finished"),
        )

try:
    tax_rate = settings.DEFAULT_TAX_RATE
except Exception:
    raise NotImplementedError()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.CASCADE)
    sub_total = models.DecimalField(default=10.99, max_digits=1000, decimal_places=2)
    tax_total = models.DecimalField(default=0.0, max_digits=1000, decimal_places=2)
    final_total = models.DecimalField(default=10.99, max_digits=1000, decimal_places=2)
    order_id = models.CharField(max_length=120, unique=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.CharField(max_length=120, choices=STATUS_CHOICES, default="Started")
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    shipping_address = models.ForeignKey(UserAddress, related_name="shipping_address", default=1, on_delete=models.CASCADE)
    billing_address = models.ForeignKey(UserAddress, related_name="billing_address", default=1, on_delete=models.CASCADE)

    def __str__(self):
        return self.order_id

    def get_final_amount(self):
        instance = Order.objects.get(id=self.id)
        tax_rate_dec = "%s" % (tax_rate)
        instance.tax_total = Decimal(tax_rate_dec) * Decimal(self.sub_total)
        instance.final_total = Decimal(self.sub_total) + Decimal(instance.tax_total)
        instance.save()
        return self.final_total

ecommerce/orders/views.py
import time
import stripe
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from carts.models import Cart
from .models import Order
from .utils import id_generator
from accounts.forms import UserAddressForm
from accounts.models import UserAddress
from django.conf import settings
from django.contrib import messages

# Create your views here.

try:
    stripe_pub = settings.STRIPE_PUBLISHABLE_KEY
    stripe_secret = settings.STRIPE_SECRET_KEY
except Exception:
    raise NotImplementedError()


stripe.api_key = stripe_secret

def orders(request):
    context = {}
    template = 'orders/user.html'
    return render(request, template, context)


@login_required
def checkout(request):

    try:
        the_id = request.session['cart_id']
        cart = Cart.objects.get(id=the_id)
    except:
        the_id=None
        return HttpResponseRedirect(reverse("cart"))

    try:
        new_order = Order.objects.get(cart=cart)
        # print("try")
    except Order.DoesNotExist:
        new_order = Order(cart=cart)
        new_order.user = request.user
        new_order.order_id = id_generator()
        new_order.save()
        print(new_order.sub_total)
    except:
        new_order = None
        return HttpResponseRedirect(reverse("cart"))

    final_amount = 0
    if new_order is not None:
        new_order.sub_total = cart.total
        new_order.save()
        final_amount = new_order.get_final_amount()

    try:
        address_added = request.GET.get("address_added")
    except:
        address_added = None

    if address_added is None:
        address_form = UserAddressForm()
    else:
        address_form = None


    current_addresses = UserAddress.objects.filter(user=request.user)
    billing_addresses = UserAddress.objects.get_billing_addresses(user=request.user)

    if request.method == "POST":
        try:
            print("hello try")
            user_stripe = request.user.userstripe.stripe_id
            customer = stripe.Customer.retrieve(user_stripe)
            # print(customer)
        except:
            print("hello except")
            customer = None
        if customer is not None:
            billing_a = request.POST['billing_address']
            shipping_a = request.POST['shipping_address']
            token = request.POST['stripeToken']

            try:
                billing_address_instance = UserAddress.objects.get(id=billing_a)
            except:
                billing_address_instance = None

            try:
                shipping_address_instance = UserAddress.objects.get(id=shipping_a)
            except:
                shipping_address_instance = None


            # card = customer.cards.create(card=token)
            # customer.source = token
            card = stripe.Customer.create_source(
                          customer.stripe_id,
                          source=token,
                        )
            card.address_city = billing_address_instance.city or None
            card.address_line1 = billing_address_instance.address or None
            card.address_line2 = billing_address_instance.address2 or None
            card.address_state = billing_address_instance.state or None
            card.address_zip = billing_address_instance.zipcode or None
            card.address_country = billing_address_instance.country or None
            card.save()

            token = request.POST['stripeToken']
            charge = stripe.Charge.create(
                      amount=int(final_amount*100),
                      currency="inr",
                      card=card,
                      customer=customer,
                      description="Charge is %s" %(request.user.username),
                    )
            print(charge)
            print(card)

            if charge["captured"]:
                new_order.status = "Finished"
                new_order.shipping_address = shipping_address_instance
                new_order.billing_addresses = billing_address_instance
                new_order.save()
                del request.session['cart_id']
                del request.session['items_total']
                messages.success(request, "Your has been completed!")
                return HttpResponseRedirect(reverse("user_orders"))

    #add shipping address
    #add billing address
    #add and return credit card
        # cart.delete()

    context = {"current_addresses": current_addresses, "billing_addresses": billing_addresses, "address_form": address_form, "stripe_pub": stripe_pub, "order": new_order}
    template = 'orders/checkout.html'
    return render(request, template, context)


def payment_view(request):
    try:
        the_id = request.session['cart_id']
        cart = Cart.objects.get(id=the_id)
    except:
        the_id=None
        return HttpResponseRedirect(reverse("cart"))

    try:
        new_order = Order.objects.get(cart=cart)
        # print("try")
    except Order.DoesNotExist:
        new_order = Order(cart=cart)
        new_order.user = request.user
        new_order.order_id = id_generator()
        new_order.save()
        print(new_order.sub_total)
    except:
        new_order = None
        return HttpResponseRedirect(reverse("cart"))

    final_amount = 0
    if new_order is not None:
        new_order.sub_total = cart.total
        new_order.save()
        final_amount = new_order.get_final_amount()

    try:
        address_added = request.GET.get("address_added")
    except:
        address_added = None

    if address_added is None:
        address_form = UserAddressForm()
    else:
        address_form = None


    current_addresses = UserAddress.objects.filter(user=request.user)
    billing_addresses = UserAddress.objects.get_billing_addresses(user=request.user)

    if request.method == "POST":
        try:
            print("hello try")
            user_stripe = request.user.userstripe.stripe_id
            customer = stripe.Customer.retrieve(user_stripe)
            # print(customer)
        except:
            print("hello except")
            customer = None
        if customer is not None:
            billing_a = request.POST['billing_address']
            shipping_a = request.POST['shipping_address']
            token = request.POST['stripeToken']

            try:
                billing_address_instance = UserAddress.objects.get(id=billing_a)
            except:
                billing_address_instance = None

            try:
                shipping_address_instance = UserAddress.objects.get(id=shipping_a)
            except:
                shipping_address_instance = None


            # card = customer.cards.create(card=token)
            # customer.source = token
            card = stripe.Customer.create_source(
                          customer.stripe_id,
                          source=token,
                        )
            card.address_city = billing_address_instance.city or None
            card.address_line1 = billing_address_instance.address or None
            card.address_line2 = billing_address_instance.address2 or None
            card.address_state = billing_address_instance.state or None
            card.address_zip = billing_address_instance.zipcode or None
            card.address_country = billing_address_instance.country or None
            card.save()

            token = request.POST['stripeToken']
            charge = stripe.Charge.create(
                      amount=int(final_amount*100),
                      currency="inr",
                      card=card,
                      customer=customer,
                      description="Charge is %s" %(request.user.username),
                    )
            print(charge)
            print(card)

            if charge["captured"]:
                new_order.status = "Finished"
                new_order.shipping_address = shipping_address_instance
                new_order.billing_addresses = billing_address_instance
                new_order.save()
                del request.session['cart_id']
                del request.session['items_total']
                messages.success(request, "Your has been completed!")
                return HttpResponseRedirect(reverse("user_orders"))

    #add shipping address
    #add billing address
    #add and return credit card
        # cart.delete()

    context = {"stripe_pub": stripe_pub, "order": new_order}
    template = 'orders/payment.html'
    return render(request, template, context)

ecommerce/templates/orders/checkout.html
{% extends "base.html" %}

<script>
{%  block jquery %}

$(".radio-label").click(function(){
  $("label").removeClass('radio-label-selected');
  $(this).addClass('radio-label-selected');
});

$(".billing-label").click(function(){
  $("label").removeClass('billing-label-selected');
  $(this).addClass('billing-label-selected');
});


  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('{{ stripe_pub }}');


jQuery(function($) {
  $('#payment-form').submit(function(event) {
    var $form = $(this);

    // Disable the submit button to prevent repeated clicks
    $form.find('button').prop('disabled', true);

    Stripe.card.createToken($form, stripeResponseHandler);

    // Prevent the form from submitting with the default action
    return false;
  });
});


function stripeResponseHandler(status, response) {
  var $form = $('#payment-form');

  if (response.error) {
    // Show the errors on the form
    $("#card_errors_div").removeClass("hidden");
    $form.find('.payment-errors').text(response.error.message);
    $form.find('button').prop('disabled', false);
  } else {
    $("#card_errors_div").addClass("hidden");
    // response contains id and card, which contains additional card details
    var token = response.id;
    // Insert the token into the form so it gets submitted to the server
    $form.append($('<input type="hidden" name="stripeToken" />').val(token));
    // and submit
    $form.get(0).submit();
  }
};


$("#addShippingAddress").click(function(e){
  e.preventDefault();
  $("#shippingAddressForm").fadeToggle();

})

{% if not current_addresses  %}
  $("#shippingAddressForm").fadeToggle();
{% endif %}

{% endblock %}
</script>

<style>
{% block styles %}

.radio-label {
  font-size: 22px;
  font-weight: normal;
  padding: 4px 30px;
  border: 1px solid #ccc;
  border-radius: 8px;
}

.radio-label input[type=radio] {
  display: none;
}

.radio-label:hover {
  font-size: 22px;
  font-weight: normal;
  background-color: #428bca;
  color: white;
  cursor: pointer;

}

.radio-label-selected {
  font-size: 22px;
  font-weight: normal;
  background-color: #428bca;
  color: white;
  cursor: pointer;
}

.billing-label {
  font-size: 22px;
  font-weight: normal;
  padding: 4px 30px;
  border: 1px solid #ccc;
  border-radius: 8px;
}

.billing-label input[type=radio] {
  display: none;
}

.billing-label:hover {
  font-size: 22px;
  font-weight: normal;
  background-color: #428bca;
  color: white;
  cursor: pointer;

}

.billing-label-selected {
  font-size: 22px;
  font-weight: normal;
  background-color: #428bca;
  color: white;
  cursor: pointer;
}




@media(min-width: 1200px) {
  .total {
    position: fixed;
  }
}

{% endblock %}
</style>


{% block content %}

<!-- <div class='col-sm-3 pull-right'>
<div class='total'>
<h1>Current total: {{ order.get_final_amount }}</h1>
<a href='#'>Finalize Checkout</a>
</div>
</div> -->

<div class='col-sm-9 pull-left'>

        <!-- Add new Shipping addres -->
        <div class='col-sm-6 pull-right' id='shippingAddressForm' style='display:none;'>
        <h3>Add new Shipping Address</h3>
        <form method="POST" action='{% url "add_user_address" %}?next=checkout'>{% csrf_token %}
        {{ address_form.as_p }}

        <input type='submit' class='btn btn-default' value='Add Shipping Address'/>
        </form>
        </div>




        <!-- current addresses -->
        <form method='POST' action="" id="payment-form">
           {% csrf_token %}
        {% if current_addresses  %}
        <div class='col-sm-12'>
        <h3>Shipping Addresses</h3>

            {% for address in current_addresses %}

            {% if request.user.userdefaultaddress.shipping.id == address.id %}
             <label class='radio-label radio-label-selected'>
            <input type='radio' name='shipping_address' value='{{ address.id }}' checked='checked'/> {{ address.get_address }}
            {% else %}
             <label class='radio-label'>
            <input type='radio' name='shipping_address' value='{{ address.id }}' /> {{ address.get_address }}

            {% endif %}
              </label><br/>
            {% endfor %}


        <a href='{% url "add_user_address" %}' id='addShippingAddress'>Add New Address</a>
        </div>
        {% endif %}





          <!-- Billing address -->
        {% if billing_addresses  %}
        <div class='col-sm-12'>
        <h3>Billing Addresses</h3>


              {% for address in billing_addresses %}

              {% if request.user.userdefaultaddress.billing.id == address.id %}
                <label class='billing-label billing-label-selected'>
              <input type='radio' name='billing_address' value='{{ address.id }}' checked='checked'/> {{ address.get_address }} <br/>
              {% else %}
              <label class='billing-label'>
              <input type='radio' name='billing_address' value='{{ address.id }}' /> {{ address.get_address }} <br/>

              {% endif %}
                </label>
              {% endfor %}

        </div>
        {% endif %}

        <div class='col-sm-6'>
        <h3>Credit Info</h3>
          <div id='card_errors_div' class="alert alert-danger hidden payment-errors" role="alert">
          </div>

          <div class="form-row">
            <div class='row'>
            <div class='col-xs-6' style='padding-right:0px;'>
            <b>Card Number</b>
              <input class='form-control' type="text" size="20" data-stripe="number"/>
            </div>
            <div class='col-xs-2'>
             <b>CVC</b>
              <input class='form-control' type="text" size="4" data-stripe="cvc"/>

            </div>

            </div>

          </div>
          <br/>

          <div class="form-row">
            <b>Expiration (MM/YYYY)</b>
            <div class='row'>

            <div class='col-xs-2' style='padding-right:0px;'>
                  <input class='form-control'  type="text" size="2" data-stripe="exp-month" placeholder='2'/>
                </div>
                <div class='col-xs-3'>
                <input  class='form-control' type="text" size="4" data-stripe="exp-year" placeholder='2017'/>
                </div>
            </div>
          </div>
          <br/>
          <br/>
          <button class='btn btn-default btn-lg' type="submit">Submit Payment</button>





        </div>
        </form>
</div>
{% endblock %}

ecommerce/templates/orders/payment.html
{% extends 'base.html' %}
<script>
    {% block jquery %}

       Stripe.setPublishableKey('{{ stripe_pub }}');

       jQuery(function($) {
    $('#payment-form').submit(function(event) {
      var $form = $(this);

        //Disable the submit button to prevent repeated clicks
      $form.find('button').prop('disabled', true);

      Stripe.card.createToken($form, stripeResponseHandler);

      // Prevent the form from submitting with the default action
      return false;
    });
  });


  function stripeResponseHandler(status, response) {
    var $form = $('#payment-form');

    if (response.error) {
      // Show the errors on the form
      $("#card_errors_div").removeClass("hidden");
      $form.find('.payment-errors').text(response.error.message);
      $form.find('button').prop('disabled', false);
    } else {
      $("#card_errors_div").addClass("hidden");
      // response contains id and card, which contains additional card details
      var token = response.id;
      // Insert the token into the form so it gets submitted to the server
      $form.append($('<input type="hidden" name="stripeToken" />').val(token));
      // and submit
      $form.get(0).submit();
    }
  };

  // $("#addShippingAddress").click(function(){
  //
  //
  // })
  // {% if current_addresses %}
  // $("#ShippingAddressForm").fadeToggle();
  // {% endif %}

    {% endblock %}
</script>
<style>
  body {
    font-family: "Montserrat", sans-serif;
    text-align: left;
    align-items: left;
    background-color: #cae8d5 !important;
  }
  h1,
  h2 {
    font-weight: 500;
  }
  .card {
    margin: 4% !important;
  }
  .payment {
    margin: 8% !important;
    margin-top: 5% !important;
  }
  .payment-title {
    font-family: "Ubuntu", sans-serif !important;

    font-size: 2.5rem;
    text-align: center;
    text-transform: uppercase;
  }
  .card-pymnt {
    margin-top: 4% !important;
    padding: 4% !important;
    padding-top: 2% !important;
    background-color: #427e92;
    color: #cae8d5;
  }
  .register-container {
    background-image: linear-gradient(
      to right,
      #204051,
      #204051,
      #427e92,
      #427e92
    );
    background-size: cover;
    background-repeat: no-repeat;
    background-attachment: fixed;
    height: auto !important;
    margin-top: 5vh !important;
    margin-bottom: 5vh !important;
  }

  .register-container p {
    font-family: "Montserrat", sans-serif;

    margin: 1rem !important;
    font-size: 1.7rem !important;
    margin-left: 15% !important;
    width: 70% !important;
    color: white;
    font-weight: bold;
    position: relative !important;

  }

  .register-container input {
    margin-left: 15% !important;
    /* width: 60% !important; */
    margin-bottom: 20px !important;
    position: relative !important;
  }
  .register-container input[type="number"] {
    width: auto !important;
    margin-left: 1% !important;
  }
  .register-container input[type="text"] {
    height: 30px;
    font-size: 16px !important;
    position: relative;
  }

  .register-container input[type="text"]:hover {
    font-size: 17px !important;
  }

  .btn-sumbit {
    margin-top: 2% !important;
    margin-left: 15% !important;
  }
</style>

{% block content %}
<!-- payment -->
<form method='POST' action="" id="payment-form">
   {% csrf_token %}
   <section
  class="payment card card-pymnt register-container"
  id="payment-section"
>
  <div class="loginbox"></div>
  <h1 class="payment-title">Credit Card Details</h1>

  <span class="payment-errors"></span>
  <div class="form-row">
    <label>
      <b>Card Number</b>
      <input type="text" size="20" data-stripe="number" name="" value="" />
    </label>
  </div>

  <div class="form-row">
    <label>
      <p>CVC</p>
      <input type="text" size="4" data-stripe="cvc" name="" value="" />
    </label>
  </div>

  <div class="form-row">
    <label>
      <p>Expiration (MM/YYYY)</p>
      <input
        style="margin-left: 15%"
        type="number"
        size="2"
        data-stripe="exp-month"
        name=""
        value=""
      />
    </label>
    <span> / </span>
    <input type="number" size="2" data-stripe="exp-year" name="" value="" />
  </div>

  <button
    style="margin-top: 2% !important; margin-left: 15% !important"
    class="btn-submit btn btn-info"
    type="submit"
    name="button"
  >
    Submit Payment
  </button>
</section>
</form>
{% endblock %}

ecommerce/templates/orders/user.html
{% extends 'base.html' %}
{% block content %}
{{ user.order_set.all }}
{% endblock %}